### PR TITLE
Add github actions for automated testing

### PR DESCRIPTION
**Pull request by houjun**
Add github actions for automated testing when a pull request is created or anything is merged to developer.
Reduce the HDF5 tests size so they can finish in 30 minutes.
Update the pytest script to run HDF5 tests separately, otherwise the second HDF5 test cannot start on the github virtual machine.
Update Makefile with the correct HDF5 flags for successful compilation in Ubuntu system.

### CODE REVIEW

**Review by andersp — COMMENTED** [review]
@houjun There are a large number of sw4img files in the PR that are shown as empty. What's going on with these files?

**Comment by houjun** [comment]
> 
> 
> @houjun There are a large number of sw4img files in the PR that are shown as empty. What's going on with these files?

It seems that github is displaying binary files as empty in the pull request, which also happened with the previous merge, it will show their actual size after the merge.

**Review by andersp — COMMENTED** [review]
@houjun why do you add so many sw4img files to the pytest/hdf5 directory? Are they really needed for the tests?

**Comment by houjun** [comment]
@andersp They are used to verify the correctness of the HDF5 image files, I can reduce the number of them.
Currently it is writing two image files every 0.5 seconds, maybe just output images at the first and last step?

**Comment by andersp** [comment]
Checking the last image would be sufficient. Please remove all the other files.

**Comment by andersp** [comment]
What happened to your last changes?
Screen Shot 2021-03-15 at 2 12 37 PM

**Comment by houjun** [comment]
@andersp I forked the repository to https://github.com/houjun/sw4 so that I can test it with github actions before this merge.

**Comment by houjun** [comment]
@andersp if there isn't any other issues, shall we merge it to developer branch?

**Review by andersp — APPROVED** [review]
Thanks for removing most of the sw4img files

**Pull request merged**
