### PR TITLE
Tang/imagehdf5

### PR DESCRIPTION
**Pull request by houjun**
- Add ZFP compression with SSI output, which buffers a number of steps before applying compression and writing to an HDF5 file
- Add a profile option (disabled by default, enable by running make profile=yes) to Makefile which uses  -g -O3", and without BZ_DEBUG to enable debug symbols while not going through time-consuming out-of-bound Sarray error checking
- Fix a compatibility issue with HDF5 1.12 and later versions.
- Passed all regression tests on Cori and Summit

### CODE REVIEW

**Comment by andersp** [comment]
@houjun in the Makefile, please add the proj variable to the list of configurable inputs. By default proj=true.

**Comment by houjun** [comment]
@andersp Just pushed an updated Makefile

**Comment by andersp** [comment]
@houjun In TimeSeries.C you have an if statement that checks if a double variable has value = 0 and then outputs "SACHDF5 possible zero value error". This might lead to a large number of error messages on stdout and may also slow down the code. I think it would be better to only include this test when compiling SW4 in debug mode.

**Comment by houjun** [comment]
@andersp Added "#if defined" statement to that error checking code

**Comment by andersp** [comment]
@houjun In parseInputFile.C there are two commands that seem to be doing the same thing: "ssioutput" and "essioutput". Why do you need both? And if you do need both, pick names that are less similar.

**Comment by houjun** [comment]
@andersp previously we used "essioutput", last month Dave suggested to call it "ssioutput", I kept both so the existing input files don't need to be changed, they are the same.

**Pull request merged**
