### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by houjun**
Add citation

### CODE REVIEW

**Comment by andersp** [comment]
Can you please put the user's guide in its own category. Also order the papers in reversed chronological order, i.e., with the (2021) at the top. Otherwise it looks very good.

**Comment by houjun** [comment]
done.

**Comment by andersp** [comment]
The report number is listed twice in the user's guide reference, i.e., "LLNL-SM-741439 (LLNL-SM-741439)". Once would be enough. Thanks

**Comment by andersp** [comment]
Looks good. I will merge once the tests have passed.

**Pull request merged**
