### PR TITLE
Time shift simulation and data to back out time offset in FWI to align with travel times 

### PR DESCRIPTION
**Pull request by wliuphd**
Introduce an optional source parameter for inversion, tshift, which is usually set to tshift=-t0 to back out time offset and align simulation with travel times estimated from the input velocity. Synthetic data generation also registers time offset t0 as origintime in output hdf5 header. 

Example usage: 
source x=6500.    y=6500.  z=8000.  Mzz=1.0 m0=1e15  t0=5.0 type=Gaussian tshift=-5.0 event=shot3 freq=3.0
tshift is set to 0 by default if not specified. 

maxstep in line search is also reverted to previous 10 for better convergence in a synthetic Gaussian anomaly test.

### CODE REVIEW

**Comment by andersp** [comment]
It seems undesirable to include an additional time shift in the source command because it makes the Timeseries class even more convoluted. We already have a center time for the source time function and it should be sufficient for calculating the time window. It would be much better to shift the time window, i.e. shift the arrival times from the Eikonal solver.

**Comment by andersp** [comment]
We can assume that t0 in the source time function corresponds to the center time. The spread of the source time function depends on the frequency resolution. With those two pieces of information you should be able to calculate the correct arrival and time windows in the pre-processing step. This approach is preferable because it is clean and easy to understand.

**Comment by wliuphd** [comment]
With the expectation that t0 in the time source function shall closely approximate the center time for different frequency band, we don't have to back out t0 for inversion. I will revise this PR to adding t0 to travel times in phase matching.

**Comment by andersp** [comment]
Sounds good. Thanks!

**Comment by andersp** [comment]
Just to make sure I understand your plan: you will change the preprocessing such that the time windows can be used directly by sw4mopt, without any shifting of the time series?

**Comment by wliuphd** [comment]
The travel time preprocessing will be only dependent on input velocity. It is processed once and the output travel times can be reused for different frequency bands. In the subsequent t FWI, time windowing will factor in frequency-dependent t0 and apply to the unshifted time series. Data and simulation time series will not be shifted.

**Comment by andersp** [comment]
@wliuphd How is your update of this PR coming along?

**Comment by wliuphd** [comment]
I have completed the revision and tested partially. I am waiting for the file system back online to complete the test before submitting for review.

**Comment by andersp** [comment]
If you are waiting for the file system CZ lustre1, you could switch to one of the other parallel file systems.

**Comment by wliuphd** [comment]
CZ lustre1 went back online this afternoon and I completed my test. I am going to close this PR and open up a new one in a moment.

**Pull request closed without merging**
