### PR TITLE
clang-format source codes

### PR DESCRIPTION
**Pull request by houjun**
Add "make format" to Makefile that uses [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to format .c .h files under src, requires clang tools (module load llvm on summit). Formatted existing codes.

### CODE REVIEW

**Comment by houjun** [comment]
Need to fix compile issues, close for now

**Comment by andersp** [comment]
Does it work on a mac?

**Comment by houjun** [comment]
> 
> 
> Does it work on a mac?
@andersp It should, you can install the tool clang-format with "brew install clang-format"

**Comment by houjun** [comment]
Closing this for more gradual code formatting changes

**Pull request closed without merging**
