### PR TITLE
Added Latex that Anders provided for Users Guide

### PR DESCRIPTION
**Pull request by drhansj**
Please try to build SW-UserGuide.tex and make sure the pdf is ok - I was successful with pdflatex on MacOS.

### CODE REVIEW

**Comment by andersp** [comment]
I can build the pdf file, but I don't see any restart documentation?

**Comment by drhansj** [comment]
Yes I wanted to get you a raw baseline first, then I’ll put in my restart content.

**Comment by drhansj** [comment]
Now has checkpoint/restart documentation, and the code works. Please review/test.

**Comment by andersp** [comment]
After reading section 11.5.5 of the user's guide, it seems the checkpoint file is always saved in the 'fileiopath' directory. But upon restart, you can specify a different directory where the checkpoint file resides. However, you also require all sac files to be in the same directory at restart. How  is that going to work in practice? Considering different striping requirements for the (very large) checkpoint file and the (small) sac files, I think they should be both written and read from separate directories. I suggest using the restartpath for both reading and writing checkpoint files. And fileiopath for both reading and writing sac files.

**Pull request merged**
