### PR TITLE
removed setting h from geodynbc

### PR DESCRIPTION
**Pull request by seanricardoford**
Setting h from whi file (geodynbc) was problematic when using refinement since grid[0] h was not the final near-surface h in the whi file.

### CODE REVIEW

**Review by andersp — COMMENTED** [review]
Looks good. Did you run the regression tests in the pytest folder?

**Comment by seanricardoford** [comment]
Just did... and failed a few, but they looked to be close to the tolerance. What do you think?

> ./test_sw4.py -d optimize_quartz_mp -n
Running all tests for level 0 ...
Test # 1 Input file: energy-nomr-2nd-1.in PASSED
Test # 2 Input file: energy-mr-4th-1.in PASSED
Test # 3 Input file: energy-mr-sg-order2-1.in PASSED
Test # 4 Input file: energy-mr-sg-order4-1.in PASSED
Test # 5 Input file: refine-el-1.in PASSED
Test # 6 Input file: refine-att-1.in PASSED
Test # 7 Input file: refine-att-2nd-1.in PASSED
Test # 8 Input file: tw-att-1.in PASSED
Test # 9 Input file: tw-att-2.in PASSED
Test # 10 Input file: tw-topo-att-1.in PASSED
Test # 11 Input file: pointsource-sg-1.in PASSED
Test # 12 Input file: flat-twi-1.in PASSED
Test # 13 Input file: flat-twi-2.in PASSED
Test # 14 Input file: gauss-twi-1.in PASSED
Test # 15 Input file: gauss-twi-2.in PASSED
Test # 16 Input file: lamb-1.in PASSED
INFO: compare_one_line: col= 1 test= 0.0076955291 base= 0.0076956781 err= 1.936151669332889e-05
ERROR: compare_one_line: err= 1.936151669332889e-05 > tolerance= 1e-05
Test # 17 Input file: gausshill-el-1.in FAILED
INFO: compare_one_line: col= 1 test= 0.0047121288 base= 0.0047127761 err= 0.00013735004300331383
ERROR: compare_one_line: err= 0.00013735004300331383 > tolerance= 1e-05
Test # 18 Input file: gauss-sg-mr-1.in FAILED
ERROR: compare_energy: line = 4 prev = 1242517.4174871736 this = 1242517.4176169643 rel diff = 1.0445788685634943e-10 > tolerance= 1e-10
Test # 19 Input file: energy-1.in FAILED
Test # 20 Input file: gausshill-att-1.in PASSED
  Running HDF5 test, may take a few minutes ...
Test # 21 Input file: loh1-h100-mr-hdf5-1.in SKIPPED
Test # 22 Input file: loh1-h100-mr-hdf5-sfile-1.in SKIPPED
Out of 22 tests, 3 failed, 17 passed, and 2 skipped

**Comment by andersp** [comment]
There is no reason why these tests should fail on quartz. Is this the code you modified?

**Comment by seanricardoford** [comment]
No, none of these are related to geodynbc. Though, I am currently trying to write a test for geodynbc so that it can be incorporated to the RAJA version - wish me luck!

**Pull request merged**
