### PR TITLE
Fix an off by 1 bug with SAC-HDF5 read buffer allocation

### PR DESCRIPTION
**Pull request by houjun**

### CODE REVIEW

**Comment by andersp** [comment]
@houjun, I am not familiar with this piece of code, but it seems odd that you would set sw4npts = npts-1 when downsample = 1. Is that really correct?

**Comment by houjun** [comment]
> 
> 
> @houjun, I am not familiar with this piece of code, but it seems odd that you would set sw4npts = npts-1 when downsample = 1. Is that really correct?

@andersp Just found that the allocateRecordingArrays() actually allocates one more element than the numberOfTimeSteps passed in, so mAllocatedSize = numberOfTimeSteps + 1, which was used in the later for loops and causing the off by 1 bug, the 1a24d1b corrects this issue by replacing mAllocatedSize in the for loops with the correct value (sw4npts=(npts - 1) * downsample + 1) and this should fix the original bug Bjorn mentioned.

**Comment by andersp** [comment]
@houjun Do you have a down sampling test that you can run to verify that it works as intended? That would be good to add to the test suite.

**Comment by bjorn2** [comment]
Houjun,
I think this will not cause memory access errors, but it will leave the last element of mRecordedSol undefined. This might lead to problems down the road. If the data on file is shorter than mRecordedSol, perhaps the undefined elements could be set to zero ?

**Comment by houjun** [comment]
> 
> 
> @houjun Do you have a down sampling test that you can run to verify that it works as intended? That would be good to add to the test suite.

I don't have a test case with down-sampled data at hand, but I can convert the current Gaussian anomaly sw4mopt test case's observation data (from Wei) to be down sampled and test it, perhaps it can be added to the sw4mopt test suite?

**Comment by houjun** [comment]
> 
> 
> Houjun,
> I think this will not cause memory access errors, but it will leave the last element of mRecordedSol undefined. This might lead to problems down the road. If the data on file is shorter than mRecordedSol, perhaps the undefined elements could be set to zero ?

@bjorn2 7006117 zero initializes the mRecordedSol and mRecordedFloats at allocation time.

**Review by bjorn2 — APPROVED** [review]

**Pull request merged**
