### PR TITLE
Sync with developer branch

### PR DESCRIPTION
**Pull request by houjun**
Following are the changes:

- Add support to read USGS GeoModelGrids data, updated the config files (use proj_6=yes instead of proj=yes, which requires proj version 6 or later, the latest 8.1.1 is recommended)
- Add support for HDF5 asynchronous I/O for checkpoint and SSI writes
- Remove etree/efile related code

### CODE REVIEW

**Comment by Ram3sh** [comment]
proj6 requires curl, ssl,sqlite and crypto ? What is it doing ?

**Comment by andersp** [comment]
@Ram3sh The proj library provides geographic projections, i.e. earth flattening schemes. To get it to build on quartz I had to first build sqlite3 and then use cmake to build proj. I had to specify the location of the sqlite3 installation with -DCMAKE_INSTALL_PREFIX. Once I got that figured it built w/o problems.

**Comment by houjun** [comment]
Latest proj library (since version 7) has some built-in tools that can download data using curl, which requires libssl and libcrypto for secure data transfer.

**Comment by Ram3sh** [comment]
OK. Does the GMG data read get tested in pytest or do you have a standalone test ?

**Comment by houjun** [comment]
I have stand-alone tests, but the GMG data file is too big (~2GB) to put in github, I'm currently reducing the size and will add a test to pytest.

**Review by Ram3sh — APPROVED** [review]

**Pull request merged**
