### PR TITLE
Tang/imagehdf5

### PR DESCRIPTION
**Pull request by houjun**
Add a HDF5 (sac and image output) test to pytest, and HDF5 I/O performance tweaking.

### CODE REVIEW

**Comment by andersp** [comment]
@houjun I get the following compilation error on the quartz machine. Perhaps an include is missing?
mpicxx -O3 -I../src  -fopenmp -DENABLE_PROJ4 -I/usr/apps/wpp/include -I../src/double -I/usr/tce/packages/hdf5/hdf5-parallel-1.10.2-intel-19.0.3-mvapich2-2.3/include -DUSE_HDF5 -c ../src/Parallel_IO.C 
../src/Parallel_IO.C(1193): error: identifier "getenv" is undefined
     char *env = getenv("HDF5_ALIGNMENT_SIZE");
                 ^

../src/Parallel_IO.C(1195): error: identifier "atoi" is undefined
         alignment = atoi(env);
                     ^

compilation aborted for ../src/Parallel_IO.C (code 2)

**Comment by houjun** [comment]
Hi @andersp , just updated the code, please try the latest version.

**Comment by andersp** [comment]
@houjun The pytest script runs very slowly on quartz and my job timed out after 30 minutes. Not sure what's going on?

**Comment by houjun** [comment]
@andersp , how many tests have finished/PASSED in your job? If you haven't already done so, try modify the mpirun_cmd in the test_sw4.py script to run the test in parallel, on Cori Haswell, it takes about 8 minutes using 8 MPI ranks and 4 omp threads per rank, on Summit, using 6 MPI ranks and 7 omp threads per rank takes a little over 5 minutes to finish all tests.

**Comment by andersp** [comment]
I don't know how many tests finished because the output is lost when the job is cancelled. Are there any special requirements on the file system when you use the parallel version of hdf5?

**Comment by houjun** [comment]
It's better to use a parallel file system, I have output directory creation failures when running on Summit's $HOME directory, it runs ok on Summit's GPFS, and there's no problem in Cori's $HOME and $SCRATCH.

**Comment by andersp** [comment]
I am trying some things out and will let you know what I find.

**Pull request merged**
